//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G02Apis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessToken
    {
        public int AccessTokenId { get; set; }
        public string Token { get; set; }
        public string UserName { get; set; }
        public System.DateTimeOffset EffectiveTime { get; set; }
        public int ExpiresIn { get; set; }
        public string UserAgent { get; set; }
        public string IP { get; set; }
    }
}
