//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G02Apis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim
    {
        public int UserClaimK { get; set; }
        public int UserFK { get; set; }
        public string Type { get; set; }
        public string Value { get; set; }
    
        public virtual User User { get; set; }
    }
}
