//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G02Apis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.JobAssignedUsers = new HashSet<JobAssignedUser>();
            this.JobWorkFlowMoves = new HashSet<JobWorkFlowMove>();
            this.JobMessages = new HashSet<JobMessage>();
            this.RegistrationJobs = new HashSet<RegistrationJob>();
            this.Schedules = new HashSet<Schedule>();
        }
    
        public System.Guid JobK { get; set; }
        public int Identity { get; set; }
        public System.Guid JobStatusFK { get; set; }
        public System.Guid JobTypeFK { get; set; }
        public bool IsActivated { get; set; }
        public System.DateTime CreatedAtUtc { get; set; }
        public int CreatedByUserFK { get; set; }
        public Nullable<System.DateTime> ModifiedAtUtc { get; set; }
        public Nullable<int> ModifiedByUserFK { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeactivatedUtc { get; set; }
        public Nullable<int> DeactivatedUserFK { get; set; }
        public System.Guid WorkflowStatusFK { get; set; }
        public string CustomerOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobAssignedUser> JobAssignedUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobWorkFlowMove> JobWorkFlowMoves { get; set; }
        public virtual ListCategory ListCategory { get; set; }
        public virtual JobType JobType { get; set; }
        public virtual WorkFlowStatu WorkFlowStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobMessage> JobMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistrationJob> RegistrationJobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedules { get; set; }
    }
}
