//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G02Apis.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MaiAnVatEntities : DbContext
    {
        public MaiAnVatEntities()
            : base("name=MaiAnVatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessToken> AccessTokens { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CategoryClassification> CategoryClassifications { get; set; }
        public virtual DbSet<FileStorage> FileStorages { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<GroupPermission> GroupPermissions { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<JobAssignedUser> JobAssignedUsers { get; set; }
        public virtual DbSet<JobAssignmentList> JobAssignmentLists { get; set; }
        public virtual DbSet<JobAssignmentListStatu> JobAssignmentListStatus { get; set; }
        public virtual DbSet<JobMessage> JobMessages { get; set; }
        public virtual DbSet<JobType> JobTypes { get; set; }
        public virtual DbSet<JobTypeWorkFlow> JobTypeWorkFlows { get; set; }
        public virtual DbSet<JobWorkFlowMove> JobWorkFlowMoves { get; set; }
        public virtual DbSet<JobWorkFlowStatu> JobWorkFlowStatus { get; set; }
        public virtual DbSet<ListCategory> ListCategories { get; set; }
        public virtual DbSet<MavMenu> MavMenus { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<PermissionType> PermissionTypes { get; set; }
        public virtual DbSet<RefreshToken> RefreshTokens { get; set; }
        public virtual DbSet<RegistrationJob> RegistrationJobs { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<ScheduleHistory> ScheduleHistories { get; set; }
        public virtual DbSet<SchemaVersion> SchemaVersions { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<UserLoginHistory> UserLoginHistories { get; set; }
        public virtual DbSet<UserNotification> UserNotifications { get; set; }
        public virtual DbSet<WorkFlowStatu> WorkFlowStatus { get; set; }
        public virtual DbSet<Claim> Claims { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
    }
}
